---
driver:
  name: vagrant
  network:
  - ["forwarded_port" , {guest: 80, host: 8080}]

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.5

suites:
  - name: default
    data_bags_path: "./../../data_bags/"
    run_list:
      - recipe[projectorion::default]
    attributes:
