---
driver:
  name: ec2
  aws_access_key_id: AKIAIRX7DMYZYGJDX67Q
  aws_secret_access_key: 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
  aws_ssh_key_id: Key
  ssh_key: C:\Users\Adam\OneDrive\Tech\Key.pem
  security_group_ids: ["sg-32fc7b57"]
  region: us-west-2
  availability_zone: us-west-2b
  require_chef_omnibus: true
  subnet_id: subnet-67856b10
  iam_profile_name: chef-client
  ssh_timeout: 10
  ssh_retries: 5
  ebs_volume_size: 6
  ebs_delete_on_termination: true
  ebs_device_name: /dev/sda
  flavor_id: t2.micro

provisioner:
  name: chef_zero

platforms:
  - name: amazon
    driver:
      image_id: ami-8bf1aebb
      username: ec2-user

suites:
  - name: default
    data_bags_path: "./../../data_bags/"
    encrypted_data_bag_secret_key_path: "./../../encrypted_data_bag_secret"
    run_list:
      - recipe[projectorion::default]
    attributes:
      projectorion:
        mysql:
          secretpath: "/tmp/kitchen/encrypted_data_bag_secret"