AWSTemplateFormatVersion: "2010-09-09"
Description: orion iam role
Resources:
  orionRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "ec2.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
  orionPolicies:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: "orionPolicy"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Action: "ec2:AssociateAddress"
            Resource: "*"
      Roles:
        -
          Ref: "orionRole"
  orionInstanceProfile:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      Path: "/"
      Roles:
        -
          Ref: "orionRole"
